# Generated by Django 5.1.5 on 2025-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('review', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('type_review', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Отзывы о компаниях',
                'verbose_name_plural': 'Отзывы о компаниях',
                'ordering': ['company_name'],
            },
        ),
    ]
