# Generated by Django 5.1.5 on 2025-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatistics',
            fields=[
                ('company_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название компании')),
                ('total_reviews', models.IntegerField(default=0)),
                ('negative_reviews', models.IntegerField(default=0)),
                ('positive_reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
