# Generated by Django 5.1.5 on 2025-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_review', '0002_reviewstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='type_review',
            field=models.BooleanField(default=True),
        ),
    ]
