# Generated by Django 5.1.5 on 2025-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_review', '0003_alter_companies_type_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='type_review',
            field=models.BooleanField(),
        ),
    ]
