# Generated by Django 5.1.5 on 2025-01-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_review', '0004_alter_companies_type_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewstatistics',
            options={'verbose_name': 'Статистика отзывов', 'verbose_name_plural': 'Статистика отзывов'},
        ),
        migrations.AddField(
            model_name='reviewstatistics',
            name='slug',
            field=models.SlugField(default=' ', max_length=255, unique=True),
        ),
    ]
