# Generated by Django 5.1.5 on 2025-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_review', '0005_alter_reviewstatistics_options_reviewstatistics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstatistics',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
