# Generated by Django 5.1.5 on 2025-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_review', '0006_alter_reviewstatistics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstatistics',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
